# permissions for end users to view os.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opensearchcluster-viewer-role
rules:
- apiGroups:
  - opensearch.org/v1
  resources:
  - opensearchcluster
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opensearch.org/v1
  resources:
  - opensearchcluster/status
  verbs:
  - get
