apiVersion: v2
name: opensearch-operator
description: The OpenSearch Operator Helm chart for Kubernetes
home: https://opensearch.org
sources:
  - https://github.com/opensearch-project/OpenSearch
  - https://github.com/opensearch-project/opensearch-k8s-operator
type: application
version: 2.8.0
appVersion: 2.8.0
