{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opensearch-operator.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opensearch-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  ports:
  - port: 443
    targetPort: {{ .Values.webhook.port }}
    protocol: TCP
    name: webhook
  selector:
    control-plane: controller-manager
{{- end }}
