{{- $labels := include "opensearch-cluster.labels" . }}
{{- $clusterName := include "opensearch-cluster.cluster-name" . }}
{{- $apiGroup := $.Values.apiGroup | default "opensearch.org" }}
{{- range .Values.users }}
---
apiVersion: {{ $apiGroup }}/v1
kind: OpensearchUser
metadata:
  name: {{ .name }}
  {{- with $.Values.cluster.annotations }}
  annotations: {{ . | toYaml | nindent 4 }}
  {{- end }}
  labels: {{ $labels | nindent 4 }}
spec:
  opensearchCluster:
    name: {{ $clusterName }}
  passwordFrom:
    name: {{ .secretName }}
    key: {{ .secretKey }}
  {{- with .backendRoles }}
  backendRoles: {{ . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .opendistroSecurityRoles }}
  opendistroSecurityRoles: {{ . | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
