name: "Docker Build"
on:
  pull_request:
    branches:
      - "main"
jobs:
  docker-build:
    name: Docker Build
    runs-on: public.ecr.aws/opsterio/go.1.17
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Docker Build
        run: |
          cd opensearch-operator
          go version
          go env
          go get opensearch.opster.io/pkg/builders
          go get opensearch.opster.io/pkg/helpers
          make docker-build
