name: Helm Docs
on:
  pull_request:
    paths: 
        - 'charts/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs: 
  helm-docs:
    name: helm docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: helm docs
        working-directory: ./opensearch-operator
        run: |
          make helm-docs
          if ! git diff --exit-code --quiet; then
            echo "Helm docs are out of date. Please run 'make helm-docs' and commit the changes."
            exit 1
          fi
