name: "Publish Release"
on:
  push:
    tags:
      - '*'
jobs:
  docker-build:
    runs-on: ubuntu-latest
    environment:
      name: k8s-operator
    container:
      image: public.ecr.aws/opsterio/go.1.17:with-aws-cli
    name: Docker Build
    steps:
      - name: Build and Push Release ARM64
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          RELEASE: ${{ env.RELEASE_VERSION }}-ARM
        run: |
          cd opensearch-operator
          go version
          go env
          go get opensearch.opster.io/pkg/builders
          go get opensearch.opster.io/pkg/helpers
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/opsterio
          docker build -f Dockerfile-ARM -t public.ecr.aws/opsterio/opensearch-operator:$RELEASE./
          docker push public.ecr.aws/opsterio/opensearch-operator:$RELEASE
          docker tag public.ecr.aws/opsterio/opensearch-operator:$RELEASE public.ecr.aws/opsterio/opensearch-operator:latest-ARM
          docker push public.ecr.aws/opsterio/opensearch-operator:latest-ARM
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: set Env
        id: github-ver
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "LATE_IMG=public.ecr.aws/opsterio/opense arch-operator:latest" >> $GITHUB_ENV
      - name: Prepare helm chart
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          pwd
          ls
          ls charts/
          echo ${{ env.RELEASE_VERSION }}
          cat charts/Chart.yaml | sed 's/0.1.0/'${{ env.RELEASE_VERSION }}'/'
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: true
      - name: Build and Push Release
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          cd opensearch-operator
          go version
          go env
          go get opensearch.opster.io/pkg/builders
          go get opensearch.opster.io/pkg/helpers
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/opsterio
          make docker-build
          make docker-push
          docker tag public.ecr.aws/opsterio/opensearch-operator:$RELEASE_VERSION public.ecr.aws/opsterio/opensearch-operator:latest
          docker push public.ecr.aws/opsterio/opensearch-operator:latest


